const loadDb = require('./loadAndDelete')
const User = require('./model/userModel')
const Tour = require('./model/tourModel')
loadDb.loadData('Natours-App',User, './dev-data/data/users.json')
// loadDb.loadData('Natours-App',Tour, './dev-data/data/tours.json')
// loadDb.deleteData('Natours-Local-DB',model)